#!/bin/bash

#

chunkc core::log_file stdout

#
# NOTE: specify the desired level of logging.
#
#       - none, debug, warn, error
#

chunkc core::log_level warn

#
# NOTE: specify the absolutepath to the directory to use when loading a plugin.
#

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins/

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 1

#
# NOTE: the following are config variables for the chunkwm-tiling plugin.
#

chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top     1
chunkc set global_desktop_offset_bottom  1
chunkc set global_desktop_offset_left    1
chunkc set global_desktop_offset_right   1
chunkc set global_desktop_offset_gap     1


chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set mouse_motion_interval         35

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        5


# NOTE: these settings require chwm-sa.
chunkc set window_float_topmost          1


# NOTE: the following are config variables for the chunkwm-border plugin.
chunkc set focused_border_color          0xffc0b18b
chunkc set focused_border_width          1
chunkc set focused_border_radius         1
chunkc set focused_border_skip_floating  0
chunkc set focused_border_skip_monocle   0


# NOTE: the following are config variables for the chunkwm-ffm plugin.
chunkc set ffm_bypass_modifier           fn


# NOTE: specify plugins to load when chunkwm starts.
chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so


# NOTE: rules for the tiling plugin
chunkc tiling::rule --owner Finder --state float &
chunkc tiling::rule --owner Deluge --state float &
chunkc tiling::rule --owner FaceTime --state float &
chunkc tiling::rule --owner TorBrowser --state float &
chunkc tiling::rule --owner \"AirBeam Pro\" --state float &
chunkc tiling::rule --owner \"System Preferences\" --subrole AXStandardWindow --state float &
chunkc tiling::rule --owner \"App Store\" --state float &
chunkc tiling::rule --owner iTunes --state float --grid-layout 6:6:1:1:4:4 &
chunkc tiling::rule --owner mpv --state float --alpha 0.65 --grid-layout 5:5:4:0:1:1 &
