let g:pymode_rope=0
let g:pymode_doc=0
let g:pymode_doc_key='K'
let g:pymode_lint =1
let g:pymode_syntax=0
let g:pymode_lint_write=0
let g:pymode_breakpoint=1
let g:pymode_breakpoint_bind = '<leader>b'
let g:pymode_lint_cwindow=0
let g:python_highlight_all=1
